# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.4’

target ’Shadow’ do

pod 'GooglePlacePicker'
pod 'GooglePlaces'
pod ‘Alamofire’
pod ’SwiftyJSON’
pod 'RSKImageCropper'
pod ‘Charts’
pod 'ICGVideoTrimmer'
use_frameworks!

end
